## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split, KFold

X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [3]:
# 前面10筆1和後面10筆0 結合
X0_train, X0_test, y0_train, y0_test = train_test_split(X[y==0], y[y==0], test_size=10)
X1_train, X1_test, y1_train, y1_test = train_test_split(X[y==1], y[y==1], test_size=10) 

# concat np array ： numpy.concatenate
x_test = np.concatenate((X0_test, X1_test))
y_test = np.concatenate((y0_test, y1_test))

print(x_test)
print(y_test)

[[945 946 947 948 949]
 [890 891 892 893 894]
 [385 386 387 388 389]
 [280 281 282 283 284]
 [695 696 697 698 699]
 [635 636 637 638 639]
 [205 206 207 208 209]
 [375 376 377 378 379]
 [295 296 297 298 299]
 [780 781 782 783 784]
 [ 55  56  57  58  59]
 [ 65  66  67  68  69]
 [ 85  86  87  88  89]
 [ 40  41  42  43  44]
 [135 136 137 138 139]
 [125 126 127 128 129]
 [ 45  46  47  48  49]
 [ 90  91  92  93  94]
 [ 80  81  82  83  84]
 [145 146 147 148 149]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
